version: '3'
services:
  chrome:
    image: robcherry/docker-chromedriver:2.38.552522
    environment:
      CHROMEDRIVER_WHITELISTED_IPS: ''
    restart: always
  app:
    depends_on:
      - chrome
    build: .
    restart: always
